#:schema node_modules/wrangler/config-schema.json
name = "clipboard"
main = "src/index.js"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "clipboard.michael-santiagog15.com", custom_domain = true }
]

[triggers]
crons = ["0 0 1 * *"]

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DATABASE"
database_name = "clipboard-db"
database_id = "1d3f9f1c-49c1-4602-b4f0-e6527afc5c33"
